name: sample
description: Flutter Dev Test.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^3.0.1+1 
  get: ^4.6.5
  json_annotation: ^4.6.0
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  jaguar_jwt: ^3.0.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  json_serializable: '>4.4.0'
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
